name: NameChanger
version: 1.0
main: com.example.myplugin.MyPlugin
api-version: 1.20
author: YourName
description: Change player display names

commands:
  setname:
    description: Change a player's display name
    usage: /setname <player> <newname>
    permission: namechanger.setname

permissions:
  namechanger.setname:
    description: Allows use of /setname
    default: op
